# Basic
title: HaiMing.Chen
subtitle: 既然选择了远方     便只顾风雨兼程
welcome_message: <a href="tencent://message/?uin=3508417&amp;Site=选择要联系我的QQ号&amp;Menu=yes" target="_blank">点击QQ与我聊天</a>
description: 嗨！我是陈海明，是一名Android开发工程师，欢迎你来到我的博客.
creator: <a href="http://www.chenhaiming.top">@chenhaiming</a>

url: "http://www.chenhaiming.top"

permalink: /:year/:month/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: 项目, description: 查看我的项目, url: 'https://github.com/Haiming-Chen'}
    - {title: 订阅, description: 邮件订阅本站, url: 'http://www.chenhaiming.top/2017/02/hello,my-blog'}
    - {title: 关于, description: 了解更多关于我, url: 'https://chm1995.github.io/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}
# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: chm1995
    github: Haiming-Chen
    twitter: 
    gplus: 
    mail: 3508417@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
    
gems: [jekyll-paginate]